/** Cover verse: Arabic is always shown; English sits under it as originally. */
export const QURAN = {
  basmala: 'بسم الله الرحمن الرحيم',
  verse:
    'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَوَدَّةً وَرَحْمَةً ۚ إِنَّ فِي ذَلِكَ لَآيَاتٍ لِقَوْمٍ يَتَفَكَّرُونَ',
  verseEn:
    'And among His signs is that He created for you spouses from yourselves, that you may find tranquility in them; and He placed between you compassion and mercy. Indeed in that are signs for people who reflect.',
  ref: 'سورة الروم · ٢١',
  refEn: 'Surah Ar-Rum · 30:21',
}

export const BLESSING = {
  ar: 'بَارَكَ اللهُ لَهُمَا وَبَارَكَ عَلَيْهِمَا وَجَمَعَ بَيْنَهُمَا فِي خَيْر',
  en: 'May Allah bless them, shower His blessings upon them, and unite them in all that is good.',
}

/** Central invitation content — edit names, date, venue, assets, and translations here. */

export const INVITATION = {
  audioSrc: '/-JUDHox3Pd8.mp3',
  audioFallback: '/audio/wedding-music.mp3',
  coupleImage: '/images/couple.jpg',
  mapsUrl:
    'https://www.google.com/maps?q=38QX%2B8C5+%D9%85%D8%B3%D8%AC%D8%AF+%D8%A7%D9%84%D8%B9%D9%84%D9%8A+%D8%A7%D9%84%D8%B9%D8%B8%D9%8A%D9%85+%D8%A7%D9%84%D9%85%D8%A7%D8%B8%D8%A9,+Almazah,+Heliopolis,+Cairo+Governorate+4461152',
  rsvpUrl:
    'https://script.google.com/macros/s/AKfycbwpQnsE4EZumwG2TopGGX-_yHNAcV0j4nqGvqvY4kUMCcyAzyHbWc56PGY2mBpk3TkHGg/exec',
  weddingDate: '2026-09-20T21:30:00',
  endDate: '2026-09-20T23:30:00',
  venueImages: [
    { src: '/images/venue/exterior.jpg', key: 'exterior' },
    { src: '/images/venue/interior.jpg', key: 'interior' },
    { src: '/images/venue/dome.jpg', key: 'dome' },
    { src: '/images/venue/details.jpg', key: 'details' },
  ],
  copy: {
    en: {
      documentTitle: 'Mohamed & Sondos — Katb Kitab',
      kicker: 'With love and joy, we welcome you',
      nameFirst: 'Mohamed',
      nameSecond: 'Sondos',
      namesLine: 'Mohamed & Sondos',
      namesScript: 'Mohamed & Sondos',
      inviteLine: 'With happy hearts, we would love you to celebrate with our family',
      coupleAlt: 'Mohamed and Sondos as children, holding hands and smiling',
      openInvite: 'Open our invitation',
      eventLabel: 'Katb Kitab',
      eventKicker: 'The celebration',
      date: '20 September 2026',
      dateShort: '20 · 09 · 2026',
      time: '9:30 PM',
      weekday: 'Sunday',
      countdown: 'Counting down',
      days: 'Days',
      hours: 'Hours',
      minutes: 'Minutes',
      seconds: 'Seconds',
      addCalendar: 'Add to Calendar',
      calendarSaved: 'Calendar event saved',
      calendarSummary: 'Wedding of Mohamed & Sondos',
      calendarLocation: 'Al-Aly Al-Azeem Mosque, Almaza, Heliopolis, Cairo, Egypt',
      calendarDescription: 'We would be honoured by your presence',
      calendarLabel: 'Katb Kitab day',
      saveTheDate: 'Save the date',
      venueKicker: 'The venue',
      venueName: 'Al-Ali Al-Azeem Mosque',
      venueArabicName: 'مسجد العلي العظيم',
      venueArea: 'Almazah, Heliopolis, Cairo, Egypt',
      venueNote: 'Please come a few minutes early so we can welcome you with love.',
      venueAlts: {
        exterior: 'Exterior of Al-Ali Al-Azeem Mosque in Almazah',
        interior: 'Ivory marble arches inside Al-Ali Al-Azeem Mosque',
        dome: 'Main dome and chandelier at Al-Ali Al-Azeem Mosque',
        details: 'Marble courtyard details at Al-Ali Al-Azeem Mosque',
      },
      locationCta: 'View Location',
      rsvpKicker: 'RSVP',
      rsvpName: 'Full name',
      rsvpNamePh: 'Your name',
      rsvpAttend: 'Will you attend?',
      rsvpYes: 'Yes, we will be there with love',
      rsvpNo: 'We send our love, and we are sorry to miss it',
      rsvpMessage: 'A little message (optional)',
      rsvpMessagePh: 'A warm word for Mohamed & Sondos…',
      rsvpSubmit: 'Submit',
      rsvpSending: 'Sending…',
      rsvpError: 'Something went wrong. Please try again.',
      rsvpThanksYes: 'We cannot wait to see you',
      rsvpThanksNo: 'You remain in our hearts',
      rsvpReceived:
        'Your yes means the world to us. We will be so happy to have our family and friends around us on this blessed day',
      rsvpDeclined:
        'Thank you for telling us with such kindness. We will miss you, and you will be in our prayers.',
      rsvpThanks: 'With all our love,',
      rsvpEdit: 'Edit response',
      closing: 'With all our love',
      photoCaption:
        'We choosed you to share our small katb ketab and we will love to see you to make our day more special',
      childhoodQuote: 'Sweet dreams to our little ones 💗',
      shareCta: 'Share invitation',
      shareText:
        'We would be honoured by your presence — 20 September 2026, 9:30 PM — Al-Aly Al-Azeem Mosque, Almaza',
      shareCopied: 'Invitation link copied',
      navHome: 'Home',
      navVenue: 'Venue',
      navRsvp: 'RSVP',
      langEn: 'EN',
      langAr: 'AR',
      langLabel: 'Language',
      musicPlay: 'Play music',
      musicPause: 'Pause music',
      musicHint: 'Tap to play music',
    },
    ar: {
      documentTitle: 'محمد و سندس — عقد القرآن',
      kicker: 'بكل حب وفرح نرحب بكم',
      nameFirst: 'محمد',
      nameSecond: 'سندس',
      namesLine: 'محمد و سندس',
      namesScript: 'محمد و سندس',
      inviteLine: 'بكل قلوبنا، يسعدنا أن تشاركونا فرحتنا مع العيلة',
      coupleAlt: 'محمد وسندس في الطفولة، يمسكان بأيدي بعضهما ويبتسمان',
      openInvite: 'افتحوا دعوتنا',
      eventLabel: 'عقد القرآن',
      eventKicker: 'المناسبة',
      date: '20 سبتمبر 2026',
      dateShort: '20 · 09 · 2026',
      time: '9:30 مساءً',
      weekday: 'الأحد',
      countdown: 'العد التنازلي',
      days: 'يوم',
      hours: 'ساعة',
      minutes: 'دقيقة',
      seconds: 'ثانية',
      addCalendar: 'أضيفوا للتقويم',
      calendarSaved: 'تم حفظ الموعد في ملف التقويم',
      calendarSummary: 'عقد قرآن محمد و سندس',
      calendarLocation: 'مسجد العلي العظيم، ألماظة، مصر الجديدة، القاهرة، مصر',
      calendarDescription: 'نتشرف بحضوركم',
      calendarLabel: 'يوم عقد القرآن',
      saveTheDate: 'احفظوا الموعد',
      venueKicker: 'المكان',
      venueName: 'مسجد العلي العظيم',
      venueArabicName: 'مسجد العلي العظيم',
      venueArea: 'ألماظة، مصر الجديدة، القاهرة، مصر',
      venueNote: 'تعالوا قبل الموعد بدقائق، لنرحب بكم بكل حب.',
      venueAlts: {
        exterior: 'واجهة مسجد العلي العظيم في ألماظة',
        interior: 'أقواس رخامية داخل مسجد العلي العظيم',
        dome: 'القبة الرئيسية داخل مسجد العلي العظيم',
        details: 'تفاصيل الصحن الرخامي في مسجد العلي العظيم',
      },
      locationCta: 'عرض الموقع',
      rsvpKicker: 'تأكيد الحضور',
      rsvpName: 'الاسم الكامل',
      rsvpNamePh: 'اسمكم',
      rsvpAttend: 'هل ستحضرون؟',
      rsvpYes: 'نعم، سنحضر بكل حب',
      rsvpNo: 'نرسل حبنا، ونعتذر عن الحضور',
      rsvpMessage: 'كلمة لطيفة (اختياري)',
      rsvpMessagePh: 'كلمة دافية لمحمد وسندس…',
      rsvpSubmit: 'إرسال',
      rsvpSending: 'جارٍ الإرسال…',
      rsvpError: 'حدث خطأ، حاولوا مرة أخرى.',
      rsvpThanksYes: 'ننتظركم بكل شوق',
      rsvpThanksNo: 'ستبقون في قلوبنا',
      rsvpReceived:
        'حضوركم يكمل فرحتنا. ننتظر لقيا العيلة والأحباب في يوم عقد قرآننا',
      rsvpDeclined:
        'شكرًا للطفكم. نفتقدكم، وتبقون في دعائنا في هذا اليوم المبارك.',
      rsvpThanks: 'بكل حبنا،',
      rsvpEdit: 'تعديل الرد',
      closing: 'بكل حبنا',
      photoCaption:
        'احنا اخترناك علشان تشاركنا فرحتنا في كتب كتابنا البسيط وهنحب جدًا نشوفك علشان يومنا يكون مميز أكتر بيك',
      childhoodQuote: 'وبنتمنى نومًا هنيئا للأطفال الصغيرين 💗',
      blessing: 'بَارَكَ اللهُ لَهُمَا وَبَارَكَ عَلَيْهِمَا وَجَمَعَ بَيْنَهُمَا فِي خَيْر',
      shareCta: 'شاركوا الدعوة',
      shareText: 'يشرفنا حضوركم — 20 سبتمبر 2026، 9:30 مساءً — مسجد العلي العظيم، ألماظة',
      shareCopied: 'تم نسخ رابط الدعوة',
      navHome: 'الرئيسية',
      navVenue: 'المكان',
      navRsvp: 'الحضور',
      langEn: 'EN',
      langAr: 'AR',
      langLabel: 'اللغة',
      musicPlay: 'تشغيل الموسيقى',
      musicPause: 'إيقاف الموسيقى',
      musicHint: 'اضغطوا لتشغيل الموسيقى',
    },
  },
}

export function detectBrowserLanguage() {
  if (typeof navigator === 'undefined') return 'en'
  const candidates = [
    navigator.language,
    navigator.userLanguage,
    ...(Array.isArray(navigator.languages) ? navigator.languages : []),
  ]
    .filter(Boolean)
    .map((code) => String(code).toLowerCase().replace('_', '-'))
  return candidates.some((code) => code === 'ar' || code.startsWith('ar-')) ? 'ar' : 'en'
}
